spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: create
        use_sql_comments: true
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL} # configuration에서 설정 필요
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_USER_PASSWORD}
#  # Overloaded POST 사용
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
## logging 레벨 설정
#    root: INFO
#    sql: ERROR
#
## session
#server:
#  servlet:
#    session:
#      timeout: 10m # 기본이 30분이고 최소는 1분입니다.